version: '3.8'

services:
  nestjs-sample-db:
    image: mysql:8.0.28
    platform: linux/x86_64
    container_name: nestjs-sample-db
    ports:
      - 3388:3306
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_DATABASE: dev
      TZ: Asia/Tokyo
    volumes:
      - ./mysql/mysql-confd:/etc/mysql/conf.d

networks:
  default:
    external: true
    name: nestjs-sample