version: '3.8'
services:
  nest-js-sample-db:
    image: mysql:8.0.27
    platform: linux/x86_64
    container_name: nest-js-sample-db
    ports:
      - '3388:3306'
    environment:
      MYSQL_ROOT_PASSWORD: dev
      TZ: Asia/Tokyo
    volumes:
      - ./mysql/mysql-confd:/etc/mysql/conf.d

networks:
  default:
    external:
      name: nest-js-sample